harmonogram/urls.py
from django.urls import path
from .views import (
	ZadanieListaWidok,
    ZadanieSzczegolyWidok,
    ZadanieDodajWidok,
    ZadanieEdytujWidok,
    ZadanieUsunWidok
    )

app_name = 'harmonogram'
urlpatterns = [
	path('', ZadanieListaWidok.as_view(), name='zadanie-lista'),
    path('dodaj', ZadanieDodajWidok.as_view(), name='zadanie-dodaj'),
    path('<int:id>/', ZadanieSzczegolyWidok.as_view(), name='zadanie-szczegoly'),
    path('<int:id>/edytuj/', ZadanieEdytujWidok.as_view(), name='zadanie-edytuj'),
    path('<int:id>/usun/', ZadanieUsunWidok.as_view(), name='zadanie-usun'),
]

konta/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

#app_name = 'konta'
urlpatterns = [
	path('', views.indexView, name="start"),
	path('dashboard/', views.dashboardView, name="dashboard"),
	path('login/',LoginView.as_view(),name="login_url"),
	path('register/',views.registerView,name="register_url"),
	path('logout/',LogoutView.as_view(next_page='start'),name="logout"),
]

zaliczenie/urls.py
from django.contrib import admin
from django.urls import include, path
from konta.views import indexView

urlpatterns = [
    path('harmonogram/', include('harmonogram.urls')),
    path('konta/', include('konta.urls')),
    path('admin/', admin.site.urls),
    path('', indexView),
]

harmonogram/models.py
from django.db import models
from django.urls import reverse

class Zadanie(models.Model):
	temat = models.CharField(max_length=150)
	opis = models.TextField(blank=False, null=False)
	uwagi = models.TextField(blank=True, null=True)
	zrealizowany = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse("harmonogram:zadanie-szczegoly", kwargs={"id": self.id}) 

harmonogram/forms.py
from django import forms

from .models import Zadanie

class ZadanieForm(forms.ModelForm):
	temat = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Wpisz temat"}))
	opis = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Dodaj opis", "rows": 20, "cols": 60}))
	uwagi = forms.CharField(required=False, widget=forms.Textarea(attrs={"placeholder": "Dodaj uwagi", "rows": 15, "cols": 50}))
	class Meta:
		model = Zadanie
		fields = [
		'temat',
		'opis',
		'uwagi',
		'zrealizowany',
		]

harmonogram/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.views.generic import (
	CreateView,
	DetailView,
	ListView,
	UpdateView,
	DeleteView
	)

from .forms import ZadanieForm
from .models import Zadanie

class ZadanieDodajWidok(CreateView):
	template_name = 'harmonogram/zadanie_dodaj.html'
	form_class = ZadanieForm
	queryset = Zadanie.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

class ZadanieEdytujWidok(UpdateView):
	template_name = 'harmonogram/zadanie_edytuj.html'
	form_class = ZadanieForm

	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(Zadanie, id=id_)

	def form_valid(self, form):
		print(form.cleaned_data)
		return super().form_valid(form)

class ZadanieUsunWidok(DeleteView):
	template_name = 'harmonogram/zadanie_usun.html'

	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(Zadanie, id=id_)

	def get_success_url(self):
		return reverse('harmonogram:zadanie-lista')

class ZadanieListaWidok(ListView):
	template_name = 'harmonogram/zadanie_lista.html'
	queryset = Zadanie.objects.all()

class ZadanieSzczegolyWidok(DetailView):
	template_name = 'harmonogram/zadanie_szczegoly.html'
	queryset = Zadanie.objects.all()

	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(Zadanie, id=id_)

konta/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def indexView(request):
	return render(request, 'index.html')
	
@login_required
def dashboardView(request):
	return render(request, 'dashboard.html')

def registerView(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('login_url')
	else:
		form = UserCreationForm()
	return render(request, 'registration/register.html', {'form':form})

harmonogram/templates/harmonogram/zadanie_dodaj.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'harmonogram:zadanie-lista' %}"><input type='submit' value='Cofnij' /></a>
<h1>Dodaj nowe zadanie:</h1>
<form action="{% url 'harmonogram:zadanie-dodaj' %}" method='POST'>{% csrf_token %}
	{{ form.as_p}}
<input type='submit' value='Zapisz' />
</form>
{% endblock %}

harmonogram/templates/harmonogram/zadanie_edytuj.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'harmonogram:zadanie-szczegoly' object.id %}"><input type='submit' value='Cofnij' /></a>
<h1>Edytuj: {{ object.id }} - {{ object.temat }}</h1>

<form action='.' method='POST'>{% csrf_token %}
	{{ form.as_p}}
<input type='submit' value='Zapisz' />
</form>
{% endblock %}

harmonogram/templates/harmonogram/zadanie_lista.html
{% extends 'base.html' %}

{% block content %}

{% for instance in object_list %}
	<p>{{ instance.id }} - <a href='{{ instance.get_absolute_url }}'>{{ instance.temat }} (Szczegóły) </a></p>
{% endfor %}

<a href="/harmonogram/dodaj"><input type='submit' value='Dodaj' /></a>

{% endblock %}

harmonogram/templates/harmonogram/zadanie_szczegoly.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'harmonogram:zadanie-lista' %}"><input type='submit' value='Cofnij' /></a>
<h1>Temat: {{ object.temat }}</h1>
<p>Opis: {{ object.opis }}</p>


<p>Uwagi: {{ object.uwagi }}</p>
<p>Zrealizowany: {{ object.zrealizowany }}</p>

<a href="{% url 'harmonogram:zadanie-edytuj' object.id %}"><input type='submit' value='Edytuj' /></a>
<a href="{% url 'harmonogram:zadanie-usun' object.id %}"><input type='submit' value='Usuń' /></a>


{% endblock %}

harmonogram/templates/harmonogram/zadanie_usun.html
{% extends 'base.html' %}

{% block content %}
<form action='.' method='POST'>{% csrf_token %}
	<h1>Czy chcesz usunąć zadanie "{{ object.temat }}"?</h1>
	<p><input type='submit' value='Tak' /> <a href='../'>Anuluj</a></p>
</form>
{% endblock %}

konta/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
	<h1>Witaj, {{user.username}}</h1>

{% endblock %}

konta/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Harmonogram Spółdzielni Świetlik</title>
</head>
<body>
	
	{% block content %}
		<h1>Harmonogram Spółdzielni Świetlik</h1>
			
			<a href="{% url 'login_url' %}">Zaloguj</a>
			<a href="{% url 'register_url' %}">Załóż konto</a>
		
	{% endblock %}
</body>
</html>

templates/base.html
<!doctype html>
<html>
<head>
	<title style="display:inline">Harmonogram Spółdzielni Świetlik</title>
</head>
<body>

	{% include 'navbar.html' %}
<a style="margin-left:50px" href="{% url 'logout' %}"><button>Wyloguj</button></a>
 {% block content %}

 {% endblock %}
</body>
</html>

templates/navbar.html
<nav>
	<h1 style="display:inline">Harmonogram zadań</h1>
</nav>